version: '3.4'

services:

  mongo:
    image: mongo:3.6.7
    ports:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongo_db:/data/db
      - mongo_configdb:/data/configdb
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
        tag: mongo
    restart: always
  
  elasticsearch:
    image: elasticsearch:5.6.12
    ports:
      - "9200"
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - elasticsearch_data:/usr/share/elasticsearch/data
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
        tag: elasticsearch
    restart: always

  graylog:
    image: graylog/graylog:2.4
    ports:
      - "9999:9000"
      - "514:514"
      - "514:514/udp"
      - "12201:12201"
      - "12201:12201/udp"
    environment:
      - GRAYLOG_WEB_ENDPOINT_URI=http://0.0.0.0:9999/api
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - graylog_data:/usr/share/graylog/data
      - ./config/graylog.conf:/usr/share/graylog/data/config/graylog.conf:ro
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: '10m'
    restart: on-failure

volumes:
  mongo_db:
  mongo_configdb:
  elasticsearch_data:
  graylog_data: